[package]
name = "ac-examples-wasm"
version = "1.16.0"
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
sp-core = { version = "35.0", default-features = false, features = ["full_crypto", "serde"] }
sp-runtime = { version = "40.1", default-features = false }
substrate-api-client = { path = "../..", version = "1.16", default-features = false }
pallet-balances = { version = "40.0", default-features = false }
