name: Test Async Examples

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-examples:
    name: Test Async Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-12-24
          components: rustfmt, clippy, rust-src
          targets: wasm32-unknown-unknown

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test -p ac-examples-async

      - name: Run clippy
        run: cargo clippy -p ac-examples-async -- -D warnings

      - name: Check formatting
        run: cargo fmt --all -- --check
